#!/bin/bash
function _get_rpm() {
	cat index.html  | \
        grep rpm | \
        awk -F "href" '{print $2}' | \
        awk -F ">" '{print $1}' | \
        awk -F "=" '{print $2}' | \
        sed "s/\"//" | sed "s/\"//" | \
        grep -v nexuiz-data
}

urls="baseurl=http://yum.theforeman.org/plugins/1.5/el6/source
baseurl=http://yum.theforeman.org/plugins/1.5/el6/x86_64
baseurl=http://yum.theforeman.org/releases/1.5/el6/source
baseurl=http://yum.theforeman.org/releases/1.5/el6/x86_64
baseurl=http://yum.puppetlabs.com/el/6/products/x86_64
baseurl=http://yum.puppetlabs.com/el/6/dependencies/x86_64
baseurl=http://yum.puppetlabs.com/el/6/devel/x86_64
baseurl=http://yum.puppetlabs.com/el/6/products/SRPMS
baseurl=http://yum.puppetlabs.com/el/6/dependencies/SRPMS
baseurl=http://yum.puppetlabs.com/el/6/devel/SRPMS
baseurl=http://repos.fedorapeople.org/repos/openstack/openstack-icehouse/epel-6/
baseurl=http://ceph.com/rpm/el6/x86_64/
baseurl=http://ceph.com/packages/ceph-extras/rpm/centos6/x86_64/
baseurl=http://download.fedoraproject.org/pub/epel/6/x86_64
baseurl=http://mirror.steadfast.net/epel/6/x86_64/
baseurl=https://repos.fedorapeople.org/repos/openstack/openstack-icehouse/epel-6/epel/
baseurl=http://rpmfind.net/linux/centos/6.5/os/x86_64/Packages/
baseurl=http://centos.mirror.nac.net/6.5/os/x86_64/Packages/
baseurl=http://mirror.cs.vt.edu/pub/CentOS/6.5/updates/x86_64/Packages/
"

for n in $urls; do
    url=`echo $n | awk -F "=" '{print $2}'`
    todir=`echo $url|awk -F"//" '{print $2}'`

    mkdir -p $todir
    old_dir=`pwd`
    cd $todir
    wget $url -O index.html
    for prpm in `_get_rpm | grep -v ceph-debuginfo`; do
        if [[ ! -e $prpm ]]; then
            nohup wget $url/$prpm >/dev/null 2>&1 &
        fi
    done
    rm -rf index.html
    cd $old_dir
done

while [[ `ps aux| grep wget | wc -l` -gt 1 ]]; do
    sleep 1
    ps aux| grep wget | wc -l
done
